{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 34557,
          "sha512": "224374a2d7927550e5ed235742a8bff899383628259367136765e52a318af458afac4977154099827ea9016e9072aa937e8dee0f3a6215cae9c7c580c13bd723",
          "sha256": "921998f3825a1514043b76e4bcc46143061e4266f4d5123b5dc1dfc88482e785",
          "sha1": "2b5bdbe397ad2fb7f21f41ab629ecdd0c8401078",
          "md5": "6717867ea5608e0dc78330a8ba382c9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.keycloak",
          "module": "keycloak-installed-adapter",
          "version": {
            "requires": "24.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 34557,
          "sha512": "224374a2d7927550e5ed235742a8bff899383628259367136765e52a318af458afac4977154099827ea9016e9072aa937e8dee0f3a6215cae9c7c580c13bd723",
          "sha256": "921998f3825a1514043b76e4bcc46143061e4266f4d5123b5dc1dfc88482e785",
          "sha1": "2b5bdbe397ad2fb7f21f41ab629ecdd0c8401078",
          "md5": "6717867ea5608e0dc78330a8ba382c9d"
        }
      ]
    }
  ]
}
