{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 34371,
          "sha512": "efb4cbcba9623ca0c0233a8c3e36e0bf562ba38aee4f9bc6698a023b72f46e9113aa6a63f01dd112135892b9127c85451bf9d125284ba6e854b68285c2762c22",
          "sha256": "1e9acbd0d3a035a0a7cd87d2bbf5fe0698cd9c73b3536e356ee3e2759a512dda",
          "sha1": "e2234a451fac27577b3f8ec979b460d0fcf4bb68",
          "md5": "9f9838f3b9b95f37c61a5e9aa83b459b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.keycloak",
          "module": "keycloak-installed-adapter",
          "version": {
            "requires": "24.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 34371,
          "sha512": "efb4cbcba9623ca0c0233a8c3e36e0bf562ba38aee4f9bc6698a023b72f46e9113aa6a63f01dd112135892b9127c85451bf9d125284ba6e854b68285c2762c22",
          "sha256": "1e9acbd0d3a035a0a7cd87d2bbf5fe0698cd9c73b3536e356ee3e2759a512dda",
          "sha1": "e2234a451fac27577b3f8ec979b460d0fcf4bb68",
          "md5": "9f9838f3b9b95f37c61a5e9aa83b459b"
        }
      ]
    }
  ]
}
