{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-client",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 70938,
          "sha512": "0c502580cd1ae233bd4b9572dbd61e12efd1602e6106c1abd7c1b391635c179bcc5cb0fbd4c37738afcf7a2c17b4feabcb1f343f77aaf8c3f1ab48789ee3bc39",
          "sha256": "fb5dc7afc98ee8c404b535d66be9b11afbf534a283c42d78c1854c46860814d7",
          "sha1": "5fc8fe1404f7d99757c00a6c5c98c4ddf347c65c",
          "md5": "61c46a0cccaaa5ed45e24efbfcd0bbe1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.keycloak",
          "module": "keycloak-installed-adapter",
          "version": {
            "requires": "24.0.3"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient-win",
          "version": {
            "requires": "4.5.14"
          }
        }
      ],
      "files": [
        {
          "name": "user-client-1.0.0.jar",
          "url": "user-client-1.0.0.jar",
          "size": 70938,
          "sha512": "0c502580cd1ae233bd4b9572dbd61e12efd1602e6106c1abd7c1b391635c179bcc5cb0fbd4c37738afcf7a2c17b4feabcb1f343f77aaf8c3f1ab48789ee3bc39",
          "sha256": "fb5dc7afc98ee8c404b535d66be9b11afbf534a283c42d78c1854c46860814d7",
          "sha1": "5fc8fe1404f7d99757c00a6c5c98c4ddf347c65c",
          "md5": "61c46a0cccaaa5ed45e24efbfcd0bbe1"
        }
      ]
    }
  ]
}
