{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-management",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-management-1.0.0.jar",
          "url": "user-management-1.0.0.jar",
          "size": 24426,
          "sha512": "df6765f8b5f9a75683096c11ea01dd92b04ec5bb8fab40a5529814ecd4eb1a5f999d856b36797596065e1b4f1747a8f48610ce66b6390d2585b33830ad39500c",
          "sha256": "477849d26a334d129867351b55b12dcca2e547198a613388a9200b03f9eabebe",
          "sha1": "5866ce8612885db63e277148c6c0fb84713daf32",
          "md5": "0cfd74fe50b22a50f19983c6f3411b87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-management-1.0.0.jar",
          "url": "user-management-1.0.0.jar",
          "size": 24426,
          "sha512": "df6765f8b5f9a75683096c11ea01dd92b04ec5bb8fab40a5529814ecd4eb1a5f999d856b36797596065e1b4f1747a8f48610ce66b6390d2585b33830ad39500c",
          "sha256": "477849d26a334d129867351b55b12dcca2e547198a613388a9200b03f9eabebe",
          "sha1": "5866ce8612885db63e277148c6c0fb84713daf32",
          "md5": "0cfd74fe50b22a50f19983c6f3411b87"
        }
      ]
    }
  ]
}
