{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-management",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-management-1.0.0.jar",
          "url": "user-management-1.0.0.jar",
          "size": 34824,
          "sha512": "4d9e7210472a3e17d1e1e12c4f58bc3157e12a23b9d6dcdc92d2029066966d8e59835198a46a35d10ad2eaa1f0d39b876bd1d309358dc516620f70c169d41158",
          "sha256": "f9a8bdbb1f70a1f9b8f95ef193a0a7c95770ac521abc48c55ba15872e905bb1a",
          "sha1": "6a7db45bf093892b07f2affc4240ce6883d48f37",
          "md5": "c8847093d11ae828cec905c6a6b35334"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "user-management-1.0.0.jar",
          "url": "user-management-1.0.0.jar",
          "size": 34824,
          "sha512": "4d9e7210472a3e17d1e1e12c4f58bc3157e12a23b9d6dcdc92d2029066966d8e59835198a46a35d10ad2eaa1f0d39b876bd1d309358dc516620f70c169d41158",
          "sha256": "f9a8bdbb1f70a1f9b8f95ef193a0a7c95770ac521abc48c55ba15872e905bb1a",
          "sha1": "6a7db45bf093892b07f2affc4240ce6883d48f37",
          "md5": "c8847093d11ae828cec905c6a6b35334"
        }
      ]
    }
  ]
}
