{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mzio",
    "module": "user-management-fx",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "user-management-fx-1.0.0.jar",
          "url": "user-management-fx-1.0.0.jar",
          "size": 50667,
          "sha512": "f58c429b444f1b98035cb6cdca60ff57120cd593b7c2a0f0600c39e62a58426ecfe1d2a0ddbde978b59f92e5f225241e7ac1be1808d40cd689940ccde11b20fd",
          "sha256": "33a3c665bca3555bd156922fcd995d6944065e69094a66cde515f5d9c0036e3a",
          "sha1": "d25ae4612a324175310f6e191735574e886cb94b",
          "md5": "3ee8ffba10a0196aba42a81790fd5eaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.controlsfx",
          "module": "controlsfx",
          "version": {
            "requires": "11.2.2"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-javafx",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-bootstrapicons-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "org.kordamp.ikonli",
          "module": "ikonli-lineawesome-pack",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-management",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "user-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.mzio",
          "module": "global-events",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.github.mzmine",
          "module": "javafx-framework"
        },
        {
          "group": "io.github.mzmine",
          "module": "taskcontroller"
        },
        {
          "group": "io.github.mzmine",
          "module": "utils"
        },
        {
          "group": "com.javax0.license3j",
          "module": "license3j",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-fxml",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "23.0.2"
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "23.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "user-management-fx-1.0.0.jar",
          "url": "user-management-fx-1.0.0.jar",
          "size": 50667,
          "sha512": "f58c429b444f1b98035cb6cdca60ff57120cd593b7c2a0f0600c39e62a58426ecfe1d2a0ddbde978b59f92e5f225241e7ac1be1808d40cd689940ccde11b20fd",
          "sha256": "33a3c665bca3555bd156922fcd995d6944065e69094a66cde515f5d9c0036e3a",
          "sha1": "d25ae4612a324175310f6e191735574e886cb94b",
          "md5": "3ee8ffba10a0196aba42a81790fd5eaa"
        }
      ]
    }
  ]
}
