# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build MZmine on OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# run on OS listed below
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
        - os: macos-11
        - os: ubuntu-latest
        - os: windows-latest
        
# Checkout OS and java version
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16 for x64
      uses: actions/setup-java@v1
      with:
        java-version: 16
        java-package: jdk # jdk+fx ?
        architecture: x64

# Cache packages
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

# build with gradlew
    - name: Build with Gradle
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --stacktrace --info
      
    - name: Upload builds
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_package_${{matrix.os}}
        path: build/jpackage/
        retention-days: 7  # store for 7 days
        
    - name: Upload builds ubuntu deb
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_package_deb_${{matrix.os}}
        path: build/jpackage/*.deb
        retention-days: 7  # store for 7 days
        
    - name: Upload builds ubuntu rpm
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_package_rpm_${{matrix.os}}
        path: build/jpackage/*.rpm
        retention-days: 7  # store for 7 days
        
    - name: Upload builds macos
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-11'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_package_${{matrix.os}}
        path: build/jpackage/*.dmg
        retention-days: 7  # store for 7 days

# clean cache important but DOES NOT WORK on windows - -f not allowed 

# Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
# Restoring these files from a GitHub Actions cache might cause problems for future builds.
    - name: Cleanup Gradle Cache
      uses: JesseTG/rm@v1.0.2 # should work on all OS but only one file at a time
      with:
        path: ~/.gradle/caches/modules-2/modules-2.lock
    - name: Cleanup Gradle Cache second file
      uses: JesseTG/rm@v1.0.2
      with:
        path: ~/.gradle/caches/modules-2/gc.properties
